apiVersion: v1
kind: ConfigMap
metadata:
  name: weight-config
data:
  PORT: "8080"
  HOST: "0.0.0.0"
  HOST_URL: http://20.76.58.192:8080
  COOKIE_ENCRYPT_PWD: superAwesomePasswordStringThatIsAtLeast32CharactersLong!
  OKTA_ORG_URL: https://dev-60980327.okta.com
