apiVersion: v1
kind: Service
metadata:
  name: weight-service
  labels:
    app: weight
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: weight